name: SonarCloud analysis

on:
  push:
    branches: [ "main", "builder" ]
  pull_request:
    branches: [ "main", "builder" ] # Include builder here as well if you want to analyze PRs to this branch.
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: |
            -Dsonar.projectKey=mo1117_Booze-Blaster
            -Dsonar.organization=mo1117
            -Dsonar.branch.name=${{ github.ref_name }}
          projectBaseDir: .
